[package]
name = "evm-from-scratch"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
primitive-types = "0.12.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
sha3  = "0.10.7"
